### ISSUE TITLE
Upload via BLE File Transfer

### ISSUE THREAD

**Issue by Brickleberry19** [solosky/pixl.js#118]
When I try to load Amiibo onto it, it mostly doesn't work.  It says that GATT is currently working or it stays at 89%.

Edit: i use the Website

**Comment by Brickleberry19** [comment]
My Laptop is the Problem, i can Upload them With my Smartphone without any problems

**Comment by solosky** [comment]
Hi, the BLE antenna is not tuned for best performance currently due to my knowledge and device limitations. 
It's barely just "usable" for BLE transmission. 
But it should have better BLE transmission speed and stability when using Mobile device connects to Pixljs with BLE connection, because the antenna for Mobile device seems has been optimized for best performance and sensitivity.
