### ISSUE TITLE
Card Details of Card Emulator types are not internationalized

### ISSUE THREAD

**Issue by impeeza** [solosky/pixl.js#165]
On the sub-menu Card Emulator -> Card Details -> Type, the names are not internationalized. may be we can include them on the .c files:
![image](https://github.com/solosky/pixl.js/assets/41979604/ca2ae4bc-4953-4fff-bbf8-fb1f8760c59d)
By example, UNDEFINED, in Spanish could be NO DEFINIDO

**Comment by solosky** [comment]
Hi, I think it's better that do not translate those words, because the card type names are kind of technical terms, I cannot find best words to translation for other languages. 

By the way, I have removed the UNDEFINED option in card type selection menu, I think the "UNDEFINED" should not be a option here.

**Comment by solosky** [comment]
see commit: https://github.com/solosky/pixl.js/commit/7c32404ebecad235d5275799aa2914a63257a253
