### ISSUE TITLE
I noticed that there is a sleep mode button in settings, what if you move it from settings next to settings

### ISSUE THREAD

**Issue by Splatboy0612** [solosky/pixl.js#286]
I think it would be easier and faster that way instead of going into settings to put the device to sleep

**Comment by MayanKoyote** [comment]
This is redundant.

Although if you look into it, this is what is currently contained in the 'Settings' section:

= Settings =
 - Version - only information
 - Language - setting
 - External Storage - information and formatting action. Well, it fits the definition of "settings", since it's set (format) storage. Although it (formatting) can also be attributed to "management".
 - Backlight - setting
 - Menu Animation - setting
 - LiPO Battery - setting
 - Memory Used - setting and information
 - Fast Wakeup - setting
 - Sleep Timeout - setting
 - Go Sleep - action. Definitely not a setting
 - Firmware Update - action. Very indirectly related to the settings (only since it's about firmware update)
 - System Reboot - action. Definitely not a setting
 - Reset Default Settings - action. But directly related to the settings
 - About Device - only information

From what is directly or indirectly not related to the settings, it's possible to compose a new separate section, let's call it 'Management':

= Management =
 - Go Sleep - action
 - System Reboot - action
 - Firmware Update - action

and if we transfer 'Firmware Update' action here, then perhaps it can also be moved here (to 'Management' section):

 - Version - only information
 - About Device - only information

So it will turn out like this:
= Management =
 - About Device - only information
 - Version - only information
 - Firmware Update - action
 - System Reboot - action
 - Go Sleep - action

**Comment by solosky** [comment]
> This is redundant.
> 
> Although if you look into it, this is what is currently contained in the 'Settings' section:
> 
> = Settings =
> 
> * Version - only information
> * Language - setting
> * External Storage - information and formatting action. Well, it fits the definition of "settings", since it's set (format) storage. Although it (formatting) can also be attributed to "management".
> * Backlight - setting
> * Menu Animation - setting
> * LiPO Battery - setting
> * Memory Used - setting and information
> * Fast Wakeup - setting
> * Sleep Timeout - setting
> * Go Sleep - action. Definitely not a setting
> * Firmware Update - action. Very indirectly related to the settings (only since it's about firmware update)
> * System Reboot - action. Definitely not a setting
> * Reset Default Settings - action. But directly related to the settings
> * About Device - only information
> 
> From what is directly or indirectly not related to the settings, it's possible to compose a new separate section, let's call it 'Management':
> 
> = Management =
> 
> * Go Sleep - action
> * System Reboot - action
> * Firmware Update - action
> 
> and if we transfer 'Firmware Update' action here, then perhaps it can also be moved here (to 'Management' section):
> 
> * Version - only information
> * About Device - only information
> 
> So it will turn out like this:
> 
> = Management =
> 
> * About Device - only information
> * Version - only information
> * Firmware Update - action
> * System Reboot - action
> * Go Sleep - action

Good point of view. 
The setttings menu sames a mess currently, I really don't give a deep thought like this. 
I may have re-structure the menu settings in future release.

**Comment by Splatboy0612** [comment]
> This is redundant.
> 
> Although if you look into it, this is what is currently contained in the 'Settings' section:
> 
> = Settings =
> 
> * Version - only information
> * Language - setting
> * External Storage - information and formatting action. Well, it fits the definition of "settings", since it's set (format) storage. Although it (formatting) can also be attributed to "management".
> * Backlight - setting
> * Menu Animation - setting
> * LiPO Battery - setting
> * Memory Used - setting and information
> * Fast Wakeup - setting
> * Sleep Timeout - setting
> * Go Sleep - action. Definitely not a setting
> * Firmware Update - action. Very indirectly related to the settings (only since it's about firmware update)
> * System Reboot - action. Definitely not a setting
> * Reset Default Settings - action. But directly related to the settings
> * About Device - only information
> 
> From what is directly or indirectly not related to the settings, it's possible to compose a new separate section, let's call it 'Management':
> 
> = Management =
> 
> * Go Sleep - action
> * System Reboot - action
> * Firmware Update - action
> 
> and if we transfer 'Firmware Update' action here, then perhaps it can also be moved here (to 'Management' section):
> 
> * Version - only information
> * About Device - only information
> 
> So it will turn out like this:
> 
> = Management =
> 
> * About Device - only information
> * Version - only information
> * Firmware Update - action
> * System Reboot - action
> * Go Sleep - action

Oh, ok, then I'll close the case
